config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :home, only: :index do
    collection do
      post :index
    end
  end

  resources :reports, only: [:index] do
    collection do
      get :index
      post :index
      post :search_zip
      post :export
      get :email
    end
  end

  namespace :api do
    namespace :v1 do
      resources :msas, only: [] do
        collection do
          get :by_zip
        end
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_zip_session

  def index
    if @zip_code.present?
      search_url  = "/api/v1/msas/by_zip?zip=#{@zip_code}"
      response    = ApiClient.new(search_url).get_url_to_json
      @error      = response['error'] if response['error'].present?
      @result     = response['data'] if @error.blank?
      @chart_data = @result.reject{ |key, value| key.exclude?('pop')} if @result.present?
    end
  rescue StandardError => e
    render json: { error: "API error occured: #{e}", status: 500 }, status: :internal_server_error
  end

  private

  def home_params
    params.permit(:zip)
  end

  def set_zip_session
    params[:zip] ||= session[:zip_code]
    session[:zip_code] = params[:zip]

    @zip_code = params[:zip]
  end
end

app/views/home/index.html.erb
<div id='main-div'>
  <div class="jumbotron">
    <div class="container" style="word-wrap: break-word; white-space: normal">
      <h1 class="display-5">Population Analyzer</h1>
      <p class="lead">Get Metropolitan Statistical Area Data by Zip Code</p>
    </div>
    <section class='row' style='margin: 0 auto;'>
      <div class='col-md-8' style='text-align: center; margin: 0 auto;'>
        <%= form_tag home_index_path, method: :post do %>
        <div class="input-group mb-3">
          <%= text_field_tag :zip, nil, placeholder: 'Enter zip code to search...', required: true, class: "form-control form-control-md"%>
          <div class="input-group-append ">
            <%= submit_tag 'Search', data: { disable_with: 'Searching...' }, class: "btn btn-md btn-outline-dark" %>
          </div>
        </div>
        <% end %>
        <%= button_to 'More Data!', search_zip_reports_path, class: "btn btn-md btn-dark" %>
      </div>
    </section>
  </div>
  <section class='row' style='margin-top: -.5em;'>
    <div class='col-md-12'>
      <% if @error %>
        <h6 class='error'><%= @error %></h6>
      <% end %>
      <% if @result %>
        <div class='row'>
          <% @result.each do |key, value| %>
            <% unless key.include?('pop') %>
              <div class='col-md-4 col-sm-4'>
                <h5><%=key.upcase%></h5>
                <p><%=value%></p>
              </div>
            <% end %>
          <% end %>
        </div>
        <div class='row' style='margin-left: 20px; margin-right: 20px;'>
          <%= column_chart @chart_data, { height: '100%', label: "Value", xtitle: "Year", ytitle: "Population" } %>
        </div>
      <% end %>
    </div>
  </section>
</div>