config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :home, only: :index do
    collection do
      post :index
    end
  end

  resources :reports, only: [:index] do
    collection do
      get :index
      post :index
      post :search_zip
      post :export
      get :email
    end
  end

  namespace :api do
    namespace :v1 do
      resources :msas, only: [] do
        collection do
          get :by_zip
        end
      end
    end
  end
end

app/models/concerns/report.rb
module Report
  def self.msa_avgs_over_years(zip_code)
    Msa.find_by_sql("
      SELECT
        name,
        (pop_estimate_2010 + pop_estimate_2011 + pop_estimate_2012 + pop_estimate_2013 + pop_estimate_2014 + pop_estimate_2015) / 6 AS avg_pop,
        (pop_change_2010 + pop_change_2011 + pop_change_2012 + pop_change_2013 + pop_change_2014 + pop_change_2015) / 6 AS avg_pop_change_blah,
        (births_2010 + births_2011 + births_2012 + births_2013 + births_2014 + births_2015) / 6 AS avg_births,
        (deaths_2010 + deaths_2011 + deaths_2012 + deaths_2013 + deaths_2014 + deaths_2015) / 6 AS avg_deaths,
        (natural_inc_2010 + natural_inc_2011 + natural_inc_2012 + natural_inc_2013 + natural_inc_2014 + natural_inc_2015) / 6 AS avg_natural_inc
      FROM msas
      JOIN cbsas_zip_codes ON msas.cbsa_id = cbsas_zip_codes.cbsa_id
      JOIN zip_codes ON zip_codes.id = cbsas_zip_codes.zip_code_id
      WHERE msas.lsad = 'Metropolitan Statistical Area'
      AND zip_codes.code = #{zip_code}
    ").first
  end

  def self.msa_natural_increase_in_county_vs_state(zip_code)
    Msa.find_by_sql("
      SELECT
        SPLIT_PART(name, ', ', 1) AS county,
        SPLIT_PART(name, ', ', 2) AS state,
        SUM(natural_inc_2010) AS county_natural_inc_2010,
        SUM(state_natural_inc_2010) AS state_natural_inc_2010,
        ROUND(SUM(natural_inc_2010) / SUM(state_natural_inc_2010) * 100::NUMERIC, 2) AS percent_of_state_2010,
        SUM(natural_inc_2011) AS county_natural_inc_2011,
        SUM(state_natural_inc_2011) AS state_natural_inc_2011,
        ROUND(SUM(natural_inc_2011) / SUM(state_natural_inc_2011) * 100::NUMERIC, 2) AS percent_of_state_2011,
        SUM(natural_inc_2012) AS county_natural_inc_2012,
        SUM(state_natural_inc_2012) AS state_natural_inc_2012,
        ROUND(SUM(natural_inc_2012) / SUM(state_natural_inc_2012) * 100::NUMERIC, 2) AS percent_of_state_2012,
        SUM(natural_inc_2013) AS county_natural_inc_2013,
        SUM(state_natural_inc_2013) AS state_natural_inc_2013,
        ROUND(SUM(natural_inc_2013) / SUM(state_natural_inc_2013) * 100::NUMERIC, 2) AS percent_of_state_2013,
        SUM(natural_inc_2014) AS county_natural_inc_2014,
        SUM(state_natural_inc_2014) AS state_natural_inc_2014,
        ROUND(SUM(natural_inc_2014) / SUM(state_natural_inc_2014) * 100::NUMERIC, 2) AS percent_of_state_2014,
        SUM(natural_inc_2015) AS county_natural_inc_2015,
        SUM(state_natural_inc_2015) AS state_natural_inc_2015,
        ROUND(SUM(natural_inc_2015) / SUM(state_natural_inc_2015) * 100::NUMERIC, 2) AS percent_of_state_2015
      FROM msas
      JOIN (
        SELECT
          SPLIT_PART(name, ', ', 2) AS state,
          SUM(natural_inc_2010) AS state_natural_inc_2010,
          SUM(natural_inc_2011) AS state_natural_inc_2011,
          SUM(natural_inc_2012) AS state_natural_inc_2012,
          SUM(natural_inc_2013) AS state_natural_inc_2013,
          SUM(natural_inc_2014) AS state_natural_inc_2014,
          SUM(natural_inc_2015) AS state_natural_inc_2015
        FROM msas
        WHERE msas.lsad = 'Metropolitan Statistical Area'
        AND SPLIT_PART(name, ', ', 2) IN (
          SELECT
            SPLIT_PART(name, ', ', 2)
          FROM msas
          JOIN cbsas_zip_codes ON msas.cbsa_id = cbsas_zip_codes.cbsa_id
          JOIN zip_codes ON zip_codes.id = cbsas_zip_codes.zip_code_id
          WHERE msas.lsad = 'Metropolitan Statistical Area'
          AND zip_codes.code = #{zip_code}
        )
        GROUP BY state
      ) state_totals ON state_totals.state = SPLIT_PART(name, ', ', 2)
      WHERE SPLIT_PART(name, ', ', 1) IN (
        SELECT
          SPLIT_PART(name, ', ', 1)
        FROM msas
        JOIN cbsas_zip_codes ON msas.cbsa_id = cbsas_zip_codes.cbsa_id
        JOIN zip_codes ON zip_codes.id = cbsas_zip_codes.zip_code_id
        WHERE msas.lsad = 'Metropolitan Statistical Area'
        AND zip_codes.code = #{zip_code}
      )
      GROUP BY 1, 2
    ").first
  end

  def self.msa_data_by_county_for_state(zip_code)
    Msa.find_by_sql("
      SELECT
        SPLIT_PART(name, ', ', 1) AS county,
        SPLIT_PART(name, ', ', 2) AS state,
        msas.*
      FROM msas
      WHERE msas.lsad = 'Metropolitan Statistical Area'
      AND SPLIT_PART(name, ', ', 2) IN (
        SELECT
          SPLIT_PART(name, ', ', 2)
        FROM msas
        JOIN cbsas_zip_codes ON msas.cbsa_id = cbsas_zip_codes.cbsa_id
        JOIN zip_codes ON zip_codes.id = cbsas_zip_codes.zip_code_id
        WHERE msas.lsad = 'Metropolitan Statistical Area'
        AND zip_codes.code = #{zip_code}
      )
    ")
  end

  def self.state_totals(zip_code)
    Msa.find_by_sql("
      SELECT
        SPLIT_PART(name, ', ', 2) AS state,
        SUM(pop_estimate_2010) AS state_pop_estimate_2010,
        SUM(pop_estimate_2011) AS state_pop_estimate_2011,
        SUM(pop_estimate_2012) AS state_pop_estimate_2012,
        SUM(pop_estimate_2013) AS state_pop_estimate_2013,
        SUM(pop_estimate_2014) AS state_pop_estimate_2014,
        SUM(pop_estimate_2015) AS state_pop_estimate_2015,
        SUM(pop_change_2010) AS state_pop_change_2010,
        SUM(pop_change_2011) AS state_pop_change_2011,
        SUM(pop_change_2012) AS state_pop_change_2012,
        SUM(pop_change_2013) AS state_pop_change_2013,
        SUM(pop_change_2014) AS state_pop_change_2014,
        SUM(pop_change_2015) AS state_pop_change_2015,
        SUM(births_2010) AS state_births_2010,
        SUM(births_2011) AS state_births_2011,
        SUM(births_2012) AS state_births_2012,
        SUM(births_2013) AS state_births_2013,
        SUM(births_2014) AS state_births_2014,
        SUM(births_2015) AS state_births_2015,
        SUM(deaths_2010) AS state_deaths_2010,
        SUM(deaths_2011) AS state_deaths_2011,
        SUM(deaths_2012) AS state_deaths_2012,
        SUM(deaths_2013) AS state_deaths_2013,
        SUM(deaths_2014) AS state_deaths_2014,
        SUM(deaths_2015) AS state_deaths_2015,
        SUM(natural_inc_2010) AS state_natural_inc_2010,
        SUM(natural_inc_2011) AS state_natural_inc_2011,
        SUM(natural_inc_2012) AS state_natural_inc_2012,
        SUM(natural_inc_2013) AS state_natural_inc_2013,
        SUM(natural_inc_2014) AS state_natural_inc_2014,
        SUM(natural_inc_2015) AS state_natural_inc_2015
      FROM msas
      WHERE msas.lsad = 'Metropolitan Statistical Area'
      AND SPLIT_PART(name, ', ', 2) IN (
        SELECT
          SPLIT_PART(name, ', ', 2)
        FROM msas
        JOIN cbsas_zip_codes ON msas.cbsa_id = cbsas_zip_codes.cbsa_id
        JOIN zip_codes ON zip_codes.id = cbsas_zip_codes.zip_code_id
        WHERE msas.lsad = 'Metropolitan Statistical Area'
        AND zip_codes.code = #{zip_code}
      )
      GROUP BY state
    ").first
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_zip_session
  before_action :verify_zip, only: :search_zip

  def index
    if @zip_code.present?
      @msa_avg_data = Report.msa_avgs_over_years(@zip_code)
      @msa_natural_increase = Report.msa_natural_increase_in_county_vs_state(@zip_code)
    end

    respond_to do |format|
      format.html
      format.json { render json: @msa_natural_increase }
    end
  end

  def search_zip
    redirect_to reports_path
  end

  def email
  end

  def export
    if reports_params[:email].present?
      ExportReportsJob.perform_now(email: reports_params[:email], zip_code: @zip_code, reports: ['msa_avgs_over_years', 'msa_natural_increase_in_county_vs_state'])
      redirect_to reports_path, notice: 'Your data is being generated and will be emailed to you.'
    else
      redirect_to email_reports_path, alert: 'Email address cannot be empty.'
    end
  rescue Net::SMTPFatalError => e
    redirect_to email_reports_path, alert: 'Please enter a valid email address.'
  end

  private

  def reports_params
    params.permit(:zip_code, :authenticity_token, :commit, :email)
  end

  def verify_zip
    ZipCodeService.new(@zip_code).verify
  rescue StandardError => e
    # remove bad zip from session
    session[:zip_code] = nil
    redirect_to reports_path, alert: e.message
  end

  def set_zip_session
    params[:zip_code] ||= session[:zip_code]
    session[:zip_code] = params[:zip_code]

    @zip_code = params[:zip_code]
  end
end

app/views/reports/email.html.erb
<div id='email-div'>
  <div class="container" style="word-wrap: break-word; white-space: normal; margin-top: 20px;">
    <h2>Export Data</h2>
    <section class='row center'>
      <div class='col-md-8' style='margin: 0 auto;'>
        <%= form_tag export_reports_path, method: :post do %>
          <div class="input-group mb-3">
            <%= text_field_tag :email, '', placeholder: 'Enter the email to send reports to', required: true, class: "form-control form-control-md"%>
            <div class="input-group-append ">
              <%= submit_tag 'Export', data: { disable_with: 'Sending...' }, class: "btn btn-md btn-outline-dark" %>
            </div>
          </div>
        <% end %>
      </div>
      <div class='container col-md-12'>
        <%= link_to 'Cancel', reports_path %>
        <% flash.each do |type, msg| %>
          <div class="<%=type%>">
            <%= msg %>
          </div>
        <% end %>
      </div>
    </section>
  </div>
</div>

app/views/reports/index.html.erb
<div id='reports-div'>
  <%= link_to 'Export Data', email_reports_path, class: 'btn btn-md btn-outline-info', style: 'margin-top: 10px; margin-right: 10px; float: right;', id: 'reports-export-btn' if @msa_avg_data %>
  <div class="container" style="word-wrap: break-word; white-space: normal; margin-top: 20px; margin-bottom: 20px;">
    <h2>Population Insights by Zip Code</h2>
    <section class='row center'>
      <div class='col-md-8' style='margin: 0 auto;'>
        <%= form_tag search_zip_reports_path, method: :post do %>
          <div class="input-group mb-3">
            <%= text_field_tag :zip_code, '', placeholder: 'Enter zip code to search...', required: true, class: "form-control form-control-md"%>
            <div class="input-group-append ">
              <%= submit_tag 'Search', data: { disable_with: 'Searching...' }, class: "btn btn-md btn-outline-dark" %>
            </div>
          </div>
        <% end %>
      </div>
      <div class='container col-md-12'>
        <% flash.each do |type, msg| %>
          <div class="<%=type%>">
            <%= msg %>
          </div>
        <% end %>
      </div>
    </section>
  </div>

  <% if @msa_avg_data.blank? %>
    <div class='container'>
      <p>No results found.</p>
    </div>
  <% else %>
    <div class='container' id='reports-div-body'>
      <div class='row'>
        <div class='col-lg-4 col-md-4 col-sm-12'>
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h4 class="card-title">Zip Code: <%=@zip_code%></h4>
              <h6 class="card-title">Area: <%=@msa_avg_data.name%></h6>
              <p class="card-text small">The following are averages for the years 2010 through 2015.</p>
              <hr>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Population Size:<h5><%=number_with_delimiter(@msa_avg_data.avg_pop)%></h5></li>
                <li class="list-group-item">Population Change:<h5><%=number_with_delimiter(@msa_avg_data.avg_pop_change_blah)%></h5></li>
                <li class="list-group-item">Births:<h5><%=number_with_delimiter(@msa_avg_data.avg_births)%></h5></li>
                <li class="list-group-item">Deaths:<h5><%=number_with_delimiter(@msa_avg_data.avg_deaths)%></h5></li>
                <li class="list-group-item">Natural Increase:<h5><%=number_with_delimiter(@msa_avg_data.avg_natural_inc)%></h5></li>
              </ul>
            </div>
          </div>
        </div>
        <div class='col-lg-8 col-md-8 col-sm-12' id='reports-natural-increase'>
        </div>
      </div>
    </div>
  <% end %>
</div>